apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-sec-filing-rag-poc
resources:
  - ../../base
  - ingress.yaml
images:
  - name: ghcr.io/hongchit/sec-filing-rag-poc-app
    newName: ghcr.io/hongchit/sec-filing-rag-poc-app
    digest: sha256:ff621fe9c203665de651f6b9c9856cd28b5fd9b57327b7e83555ff73f830f333
  - name: ghcr.io/hongchit/sec-filing-rag-poc-postgres
    newName: ghcr.io/hongchit/sec-filing-rag-poc-postgres
    digest: sha256:d24f69d5405177c33e19874af63820e0f9b7e79ce4148bf6ff4eae6ff6fac016
patches:
  - path: app-environment.yaml
