apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: project-sec-filing-rag-poc
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 7Gi
    requests.storage: 25Gi
    persistentvolumeclaims: "4"
    pods: "10"
